# Generated by Django 5.0.1 on 2024-02-09 01:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Post",
        ),
        migrations.RemoveField(
            model_name="person",
            name="address",
        ),
        migrations.RemoveField(
            model_name="person",
            name="age",
        ),
        migrations.RemoveField(
            model_name="person",
            name="email",
        ),
        migrations.RemoveField(
            model_name="person",
            name="github",
        ),
        migrations.RemoveField(
            model_name="person",
            name="phone",
        ),
    ]
