# Generated by Django 5.0.1 on 2024-02-09 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_delete_post_remove_person_address_remove_person_age_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="address",
            field=models.CharField(default="1234 Main St", max_length=100),
        ),
        migrations.AddField(
            model_name="person",
            name="email",
            field=models.EmailField(default="sujan@nibba.com", max_length=254),
        ),
        migrations.AddField(
            model_name="person",
            name="github",
            field=models.URLField(default="github.com/sujan-nibba"),
        ),
        migrations.AddField(
            model_name="person",
            name="phone",
            field=models.CharField(default="1234567890", max_length=15),
        ),
        migrations.AlterField(
            model_name="person",
            name="first_name",
            field=models.CharField(default="John", max_length=30),
        ),
        migrations.AlterField(
            model_name="person",
            name="last_name",
            field=models.CharField(default="Doe", max_length=30),
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Title", max_length=100)),
                ("content", models.TextField(default="Content")),
                ("date_uploaded", models.DateTimeField(auto_now_add=True)),
                ("url", models.URLField(default="https://www.google.com")),
                (
                    "contributor",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.person",
                    ),
                ),
            ],
        ),
    ]
