# Generated by Django 5.0.2 on 2024-02-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_post_cover_image_comment_image_post_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="images",
        ),
        migrations.AddField(
            model_name="post",
            name="repository",
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
