# Generated by Django 5.0.1 on 2024-02-09 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_person_address_person_email_person_github_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="username",
            field=models.CharField(default="sujannibba", max_length=30),
        ),
        migrations.AlterField(
            model_name="post",
            name="contributor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="home.person"
            ),
        ),
    ]
