# Generated by Django 5.0.2 on 2024-02-11 04:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_remove_post_images_post_repository"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
