# Generated by Django 5.0.2 on 2024-02-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_member_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
