# Generated by Django 5.0.2 on 2024-02-11 05:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_post_username"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="username",
        ),
        migrations.AddField(
            model_name="post",
            name="contributors",
            field=models.ManyToManyField(
                blank=True, related_name="contributors", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
