# Generated by Django 5.0.2 on 2024-02-11 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_remove_post_username_post_contributors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="home.member"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="contributors",
            field=models.ManyToManyField(
                blank=True, related_name="contributors", to="home.member"
            ),
        ),
    ]
