# Generated by Django 5.0.2 on 2024-02-11 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_alter_post_author_alter_post_contributors"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="member",
            name="email",
        ),
        migrations.RemoveField(
            model_name="member",
            name="name",
        ),
        migrations.RemoveField(
            model_name="member",
            name="password",
        ),
        migrations.RemoveField(
            model_name="member",
            name="username",
        ),
        migrations.AddField(
            model_name="member",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
