# Generated by Django 5.0.2 on 2024-02-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_remove_member_date_joined_remove_member_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
