# Generated by Django 5.0.2 on 2024-02-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0009_member_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="user",
        ),
        migrations.AddField(
            model_name="member",
            name="date_joined",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="password",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="github",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
