# Generated by Django 5.0.2 on 2024-02-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0016_alter_image_author_alter_member_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="cover_image",
            field=models.ImageField(blank=True, upload_to="posts/"),
        ),
    ]
